project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!slides/to-come"
    - "!labs/keys"
    - "!resources"

website:
  title: "ESS 523c"
  favicon: favicon.ico
  navbar:
    background: "#1E4D2B"
    foreground: "#C8C372"
    pinned: true
    logo: csu-rams-logo.png
    favicon: favicon.ico
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/mikejohnson51/csu-ess-523c/
        aria-label: ESS 523c

format:
  html:
    theme: 
      light: flatly
      dark:  darkly
    css: styles.css
    toc: true
    
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"